language: rust
rust:
  - nightly
  - stable
  # The following Rust version represents the oldest supported version of Mio.
  # This value should not be changed without prior discussion.
  - 1.9.0

os:
  - linux
  - osx

matrix:
    allow_failures:
        - rust: nightly

script:
  - cargo test
  - cargo doc --no-deps

# Deploy documentation to S3 for specific branches. At some
# point, it would be nice to also support building docs for
# a specific tag
deploy:
  provider: s3
  access_key_id: AKIAISVZFP2MDUU6KA5A
  secret_access_key:
    secure: DsarqYqQzaRus/1m4k4aa9tF+ciVN28UKIYap91EK34KYZmyKslG7O+tSNEqfQV3zq4iO6OLh8s2Gzs+sA0f+OSbDcsL9F5uZcvRVwejgvP91zsHPUzmi6Rb6AlIqnwGE/PQ7vUYxJWrRlNKe6ZUAH5w20h5yRUybZKQIS99PoQ=
  bucket: rust-doc
  skip_cleanup: true
  local-dir: target/doc
  upload-dir: mio/${TRAVIS_BRANCH}
  acl: public_read
  on:
    condition: $TRAVIS_RUST_VERSION == "1.8.0" && $TRAVIS_OS_NAME == "linux"
    repo: carllerche/mio
    branch:
      - master
